### ISSUE TITLE
infinite loop to download the models required by RePlay on Linux Mint

### ISSUE THREAD

**Issue by CodesoundR** [sb-ai-lab/RePlay#66]
## 🐛 Bug

Linux Mint 21.2_x64 - Replay-3.2.4.deb

Even if you have downloaded the models, it does not allow you to press the "continue" button

https://imgur.com/RJafAQr

greetings and thanks for everything

**Comment by OnlyDeniko** [comment]
@CodesoundR As I see probably you're trying to use another RePlay, not our product

Also I see you use Replay version 3.2.4 - our latest version is 0.15.0



If I'm not right and you use our RePlay, let us know

**Comment by CodesoundR** [comment]
My apologize! I wrong the repository...... Delete this post/issue..... thanks for alll

**Comment by AleXXL1** [comment]
it is an invalid bug.
